name = "SkjiPack"
author = "skji and fwends"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "154507266badf4f09a060fd92f083cf6b609242f18cd60eba9a023085c1aa210"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
